title: moo - The tech consultants
description: moo is a tech consultancy company that aims to solve tough problems with technology. We advise, train, audit and research for companies all over the world
url: https://moo.mt
email: info@moo.mt
exclude: [".jekyll-cache", ".bundle", ".github", "Gemfile*", ".gitignore", "GitVersion.yml", ".git", "README.md", ".kodiak.toml", ".nojekyll", "LICENSE"]
ver: 0.0.0-local
google_analytics: G-VB25BQCDFK
livereload: true
theme-color: "#F7F7F7"
host: 0.0.0.0